select ename, job from emp;
select * from emp where deptid = 20;
select ename, sal * 1.7 as increased_salary from emp;
select * from emp where sal > 2000 and sal < 4000;
select * from emp where job in ('manager', 'analyst');
select * from emp where sal not between 1000 and 3000;
select * from emp where ename like 's%';
select * from emp where mgr is null;
select sum(sal) as total_salary from emp;
select deptid, max(sal) as max_salary from emp group by deptid;
select * from emp order by sal desc;
select ename from emp where sal > (select avg(sal) from emp);
select * from emp e where sal = (select max(sal) from emp where deptid = e.deptid);
select max(sal) as second_highest from emp where sal < (select max(sal) from emp);
select e.ename, d.dname from emp e inner join dept d on e.deptid = d.deptid;
select e.ename, d.deptid from emp e left join dept d on e.deptid = d.deptid;
select e.ename, d.deptid from emp e right join dept d on e.deptid = d.deptid;
select e.ename, d.deptid from emp e left join dept d on e.deptid = d.deptid union select e.ename, d.deptid from emp e right join dept d on e.deptid = d.deptid;
select * from emp natural join dept;
select * from emp cross join dept;
select a.ename as employee, b.ename as manager from emp a join emp b on a.empno = b.empno;
select * from emp where sal > (select sal from emp where ename = 'scott');
select deptid from emp group by deptid having max(sal) > 3000;
select max(sal) as third_highest from emp where sal < (select max(sal) from emp where sal < (select max(sal) from emp));
select min(sal) as second_lowest from emp where sal > (select min(sal) from emp);
select * from emp where job <> 'clerk' and sal > 2000;
select * from emp where ename like '%r';
select * from emp where deptid in (10, 30);
select deptid, avg(sal) as avg_sal from emp group by deptid having avg(sal) > 2000;
select deptid, count(*) as emp_count from emp group by deptid having count(*) > 2;
select job, max(sal) as max_sal, avg(sal) as avg_sal from emp group by job having max(sal) > 3000;
select deptid, sum(sal) as total_salary from emp group by deptid having sum(sal) between 5000 and 10000;
select deptid, sum(sal) as total_sal from emp group by deptid;
select deptid, sum(sal) as total_sal from emp group by deptid having sum(sal) > 7000;